version: '3.1'

networks:
  database-to-dotnet-network:
    driver: bridge

services:
 openComputingLabFrontend:
  image: 'vuci359/fer3_opencomputing_lab_exam:frontend_v3'
  container_name: opencomputingLabFrontend
  ports:
   - "80:80"
  networks:
   - database-to-dotnet-network

 opencomputingLabBackend:
  image: 'vuci359/fer3_opencomputing_lab_exam:backend_v3'
  container_name: opencomputingLabBackend
  ports: 
   - "8087:8080"
  networks:
   - database-to-dotnet-network
  depends_on:
    opencomputingLabDatabase:
      condition: service_healthy
  environment:
   - ASPNETCORE_URLS=http://+:8080/
 
 opencomputingLabDatabase:
  image: 'vuci359/fer3_opencomputing_lab_exam:database_v3'
  container_name: opencomputingLabDatabase
  environment:
   - POSTGRES_USER=postgres
   - POSTGRES_PASSWORD=r/)&kjnkeVNSEHUE83
  ports:
   - "5435:5432"
  networks:
   - database-to-dotnet-network
  healthcheck:
   test: ["CMD-SHELL", "pg_isready -U postgres"]
   interval: 5s
   timeout: 5s
   retries: 5

