version: '3.1'

services:
 openComputingLabFrontend:
  image: 'vuci359/fer3_opencomputing_lab_exam:frontend_v1'
  container_name: opencomputingLabFrontend
  ports:
   - "80:80"

 opencomputingLabBackend:
  image: 'vuci359/fer3_opencomputing_lab_exam:backend_v1'
  container_name: opencomputingLabBackend
  ports: 
   - "8087:8080"
   - "8000:8000"
  depends_on:
    opencomputingLabDatabase:
      condition: service_healthy
  environment:
   - ASPNETCORE_URLS=http://+:8000
 
 opencomputingLabDatabase:
  image: 'vuci359/fer3_opencomputing_lab_exam:database_v1'
  container_name: opencomputingLabDatabase
  environment:
   - POSTGRES_USER=postgres
   - POSTGRES_PASSWORD=r/)&kjnkeVNSEHUE83
  ports:
   - "5435:5432"
  healthcheck:
   test: ["CMD-SHELL", "pg_isready -U postgres"]
   interval: 5s
   timeout: 5s
   retries: 5

