version: '3.1'

services:
 opencomputingLabDatabase:
  image: 'vuci359/fer3_opencomputing_lab_exam:baza'
  container_name: opencomputingLabDatabase
  environment:
   - POSTGRES_USER=postgres
   - POSTGRES_PASSWORD=r/)&kjnkeVNSEHUE83
  ports:
   - "5435:5432"
